version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"

  backend_app:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - "3306:3306"
    volumes:
      - bdms-vol:/var/lib/mysql

volumes:
  bdms-vol: